version: '3.8'
services:
  db:
    image: postgres:13 # Oder eine neuere Version
    container_name: timerecording_db
    environment:
      POSTGRES_USER: timerecording_user
      POSTGRES_PASSWORD: secure_password123
      POSTGRES_DB: timerecording
    ports:
      - "5432:5432" # Port am Host : Port im Container
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: time-recording-backend:0.0.1-SNAPSHOT # Name des lokal gebauten Images
    container_name: timerecording_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Überschreibt die Einstellungen in application.properties
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/timerecording # 'db' ist der Service-Name der Datenbank
      SPRING_DATASOURCE_USERNAME: timerecording_user
      SPRING_DATASOURCE_PASSWORD: secure_password123
      # Optional: JWT Secret und andere Konfigurationen als Umgebungsvariablen
      # APP_JWTSECRET: euer_geheimnis
    # Wenn ihr das Image nicht lokal gebaut habt, sondern z.B. von Docker Hub laden würdet:
    # build: . # Alternativ, wenn ein Dockerfile im Projekt liegt

volumes:
  postgres_data: # Definiert ein persistentes Volume für die Datenbank